sudo: false
language: android
jdk:
  - oraclejdk8
android:
  components:
  - tools # to get the new `repository-11.xml`
  - platform-tools
  - tools # to install Android SDK tools 25.1.x (x = 7 right now)
  - build-tools-24.0.1
  - android-$EMULATOR_TARGET
  - android-$ANDROID_API_LEVEL
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-$EMULATOR_TARGET
before_install:
  - echo no | android create avd --force -n test -t "android-"$EMULATOR_TARGET --abi $ANDROID_ABI -c 20M
  - emulator -avd test -no-skin -no-audio -no-window &
  - chmod +x ./wait_for_emulator.sh
  - ./wait_for_emulator.sh
script:
# build app and assemble APK, in debug mode
  - ./gradlew assembleDebug
# run all the local unit tests of app module
  - ./gradlew :testDebug
# run all the instrumented tests of app module - DISABLED until we get an stable setup for Espresso in Travis
# - ./gradlew connectedDebugAndroidTest --info
# install app, then assemble and install instrumented tests of app module
  - ./gradlew :installDebug
  - ./gradlew :installDebugAndroidTest
# run sample instrumented unit test
  - adb shell am instrument -w -e debug false -e class com.owncloud.android.datamodel.OCFileUnitTest com.owncloud.android.test/android.support.test.runner.AndroidJUnitRunner
env:
  global:
  - secure: h4Y7ZvgbvOj5T71ubRcw3Fy3KXF8qHugRFLGK3q2R9YuRsDAf8XH+Y/UiXyH8sac2QSj7Zlny1kA1DEJgwhTXs9wsAVKVJCQNTJGEvhm/4uQgPeNMzMv07Lqe8V+KUBsFH5qhfPJO357ERW0k2f2qljoLSHtHStclt7iGvFdynA=
  - secure: o9L6lXWpXowhQSdiUSmajliBUkQ6n7NrBUqhC09lqe7yXSGhEsgGRXqHoT3q2B4uIqGSiLCa9HQbW0dfDQCs+pADmzHIl3zbTViR88TSaIhOiTrqMUUl5iaO++pneZ2TzgU9bbGHbl6Ixjc6iALH2+F7P+RUM6vLTNPcfnCJa3g=
  - secure: ydxZrS7+1ht3p1tC6DE9W9bjLQGjMkwFBwyhNmcdEM6538kN8ZCBQe7NxSsCrC1nSDBLQ17Cziv0XJHl/pCfPrbkrPPgVFpjDfPeqC2zcGcCNcFQUEylXCvQ4uRU2hKL6dPqCsOQ57Pv3qwpPoprl/usoN5Wh8V7BKplU88ZaYM=
  matrix:
  - ANDROID_API_LEVEL=24 ANDROID_ABI=armeabi-v7a EMULATOR_TARGET=23
