sudo: false
language: android
android:
  components:
    - build-tools-22.0.1
    - android-22
before_install:
  - rm pom.xml
script:
  - ./setup_env.sh ant
  - ant clean -Djava.source=7 -Djava.target=7
  - ant debug -Djava.source=7 -Djava.target=7
  
