sudo: false
language: android
android:
  components:
    - build-tools-23.0.2
    - android-23
    - android-22
    - android-19
before_install:
  - rm pom.xml
script:
  - ./setup_env.sh ant
  - ant clean -Djava.source=7 -Djava.target=7
  - ant debug -Djava.source=7 -Djava.target=7
  
