sudo: false
language: android
android:
  components:
    - build-tools-23.0.3
    - android-23
    - android-22
    - android-19
script:
  - ./setup_env.sh ant
  - ant clean -Djava.source=7 -Djava.target=7
  - ant debug -Djava.source=7 -Djava.target=7
  
